

export  const data = [
    {id:1,name:'babu',
    mail:'babu@mail.com',
    img:"https://static.vecteezy.com/system/resources/previews/011/675/382/original/man-avatar-image-for-profile-png.png"},
    {id:2,name:'mani',
    mail:'mani@mail.com',
    img:"https://png.pngtree.com/png-vector/20220709/ourmid/pngtree-businessman-user-avatar-wearing-suit-with-red-tie-png-image_5809521.png"},
    {id:3,name:'nagu',
    mail:'nagu@mail.com',
    img:"https://www.shutterstock.com/image-vector/young-smiling-man-avatar-brown-600nw-2261401207.jpg"},
    {id:4,name:'hari',
    mail:'hari@mail.com',
    img:"https://img.freepik.com/free-vector/businessman-character-avatar-isolated_24877-60111.jpg"},
    {id:5,name:'jhon',
    mail:'jhon@mail.com',
    img:"https://png.pngtree.com/png-vector/20220807/ourmid/pngtree-man-avatar-wearing-gray-suit-png-image_6102786.png"},
    {id:6,name:'karthi',
    mail:'karthi@mail.com',
    img:"https://static.vecteezy.com/system/resources/thumbnails/002/002/403/small/man-with-beard-avatar-character-isolated-icon-free-vector.jpg"},
     {id:7,name:'harish',
    mail:'harish@mail.com',
    img:"https://img.freepik.com/free-psd/3d-illustration-person-with-sunglasses_23-2149436188.jpg"},
    {id:8,name:'Mathew',
    mail:'Mathew@mail.com',
    img:"https://static.vecteezy.com/system/resources/thumbnails/009/397/835/small/man-avatar-clipart-illustration-free-png.png"},
    {id:9,name:'leo',
    mail:'leo@mail.com',
    img:"https://imgv3.fotor.com/images/gallery/american-anime-stule-naked-man-avatar.jpg"},
    {id:10,name:'das',
    mail:'das@mail.com',
    img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSPFNeUn89NkscCQdePBFlIp7ixL81eU9pY3g&usqp=CAU"},
];